#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"

source "$SCRIPT_DIR/bin/common.sh"
source "$SCRIPT_DIR/venv/bin/activate"

echo "▖  ▖   ▌ ▌   ▌  ▄▖    ▜   "
echo "▛▖▞▌▛▌▛▌▛▌█▌▛▌  ▐ ▛▌▛▌▐ ▛▘"
echo "▌▝ ▌▙▌▙▌▙▌▙▖▙▌  ▐ ▙▌▙▌▐▖▄▌"
echo "by jack"
echo "Select one option using up/down keys and enter to confirm:"
echo

scripts=(
    "$SCRIPT_DIR/bin/build.sh"
    "$SCRIPT_DIR/bin/runclient.sh"
    "$SCRIPT_DIR/bin/runserver.sh"
    "$SCRIPT_DIR/bin/spotless.sh"
    "$SCRIPT_DIR/bin/invoke_langmanager.sh"
    "$SCRIPT_DIR/bin/publish_to_maven.sh"
    "$SCRIPT_DIR/bin/transform_readme.py"
    "$SCRIPT_DIR/bin/update_forge_readme.sh"
    "$SCRIPT_DIR/bin/update_modrinth_readme.sh"
    "$SCRIPT_DIR/bin/update_67minecraft_readme.sh"
    "$SCRIPT_DIR/bin/update_buildscript.sh"
    "$SCRIPT_DIR/bin/check_dependency_updates.sh"
    "$SCRIPT_DIR/bin/setup_github_credentials.sh"
)
options=(
    "Build Mod"
    "Run Client"
    "Run Server"
    "Apply Spotless"
    "Apply LangManager"
    "Publish to Maven"
    "Transform Readme"
    "Update Curse Readme"
    "Update Modrinth Readme"
    "Update 67Minecraft Readme"
    "Update Buildscript"
    "Check Dependencies For Updates"
    "Setup GitHub Credentials (Folder)"
)

select_option "${options[@]}"
choice=$?

${scripts[$choice]}
